* 자료출처: https://www.data.go.kr/data/15012896/standard.do

In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("dataset/서울주차장정보표준데이터.csv", encoding="cp949")
df.shape

(514, 31)

In [12]:
df.head(10)

,주차장관리번호,주차장명,주차장구분,주차장유형,소재지도로명주소,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,108-1-000030,아카데미,공영,노상,서울특별시 강북구 4.19로25길,서울특별시 강북구 인수동 543-76,37,3,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108-2-000026,수유쌈지,공영,노외,서울특별시 강북구 도봉로 265,서울특별시 강북구 수유동 612-6,19,1,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,108-1-000031,교육청길,공영,노상,서울특별시 강북구 도봉로20가길 3,서울특별시 강북구 송중동 137-19,80,3,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,108-2-000016,오패산,공영,노외,서울특별시 강북구 도봉로34길 54,서울특별시 강북구 미아동 133-100,76,5,미시행,평일+토요일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,108-2-000005,미아동,공영,노외,서울특별시 강북구 도봉로61길 46,서울특별시 강북구 미아동 222-100,155,5,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,108-2-000007,수유마을시장,공영,노외,서울특별시 강북구 도봉로69길 29,서울특별시 강북구 수유1동 55-53,116,5,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,108-2-000025,송중동(임시),공영,노외,서울특별시 강북구 도봉로8길 67,서울특별시 강북구 미아동 860-123,6,3,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,108-1-000029,벽산,공영,노상,서울특별시 강북구 삼각산로 140,서울특별시 강북구 수유동 36-1,36,3,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,108-2-000015,냉천길,공영,노외,서울특별시 강북구 삼양로 230-12,서울특별시 강북구 미아동 756-1,104,3,미시행,평일+토요일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,108-2-000004,교통광장,공영,노외,서울특별시 강북구 삼양로 678,서울특별시 강북구 우이동 265,158,3,미시행,평일+토요일+공휴일,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   주차장관리번호      514 non-null    object
 1   주차장명         514 non-null    object
 2   주차장구분        514 non-null    object
 3   주차장유형        514 non-null    object
 4   소재지도로명주소     382 non-null    object
 5   소재지지번주소      478 non-null    object
 6   주차구획수        514 non-null    int64
 7   급지구분         514 non-null    object
 8   부제시행구분       514 non-null    object
 9   운영요일         514 non-null    object
 10  평일운영시작시각     514 non-null    object
 11  평일운영종료시각     514 non-null    object
 12  토요일운영시작시각    514 non-null    object
 13  토요일운영종료시각    514 non-null    object
 14  공휴일운영시작시각    514 non-null    object
 15  공휴일운영종료시각    514 non-null    object
 16  요금정보         514 non-null    object
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  Unnamed: 23  0 non-null      float64
 24  Unnamed: 24  0 non-null      float64
 25  Unnamed: 25  0 non-null      float64
 26  Unnamed: 26  0 non-null      float64
 27  Unnamed: 27  0 non-null      float64
 28  Unnamed: 28  0 non-null      float64
 29  Unnamed: 29  0 non-null      float64
 30  Unnamed: 30  0 non-null      float64
dtypes: float64(14), int64(1), object(16)
memory usage: 124.6+ KB

In [16]:
df =df.drop(columns = ['Unnamed: 17',
                  'Unnamed: 18',
                  'Unnamed: 19',
                  'Unnamed: 20',
                  'Unnamed: 21',
                  'Unnamed: 22',
                  'Unnamed: 23',
                  'Unnamed: 24',
                  'Unnamed: 25',
                  'Unnamed: 26',
                  'Unnamed: 27',
                  'Unnamed: 28',
                  'Unnamed: 29',
                  'Unnamed: 30'])

In [17]:
df.head()

,주차장관리번호,주차장명,주차장구분,주차장유형,소재지도로명주소,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,평일운영종료시각,토요일운영시작시각,토요일운영종료시각,공휴일운영시작시각,공휴일운영종료시각,요금정보
0,108-1-000030,아카데미,공영,노상,서울특별시 강북구 4.19로25길,서울특별시 강북구 인수동 543-76,37,3,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
1,108-2-000026,수유쌈지,공영,노외,서울특별시 강북구 도봉로 265,서울특별시 강북구 수유동 612-6,19,1,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
2,108-1-000031,교육청길,공영,노상,서울특별시 강북구 도봉로20가길 3,서울특별시 강북구 송중동 137-19,80,3,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
3,108-2-000016,오패산,공영,노외,서울특별시 강북구 도봉로34길 54,서울특별시 강북구 미아동 133-100,76,5,미시행,평일+토요일,0:00,23:59,0:00,23:59,0:00,0:00,유료
4,108-2-000005,미아동,공영,노외,서울특별시 강북구 도봉로61길 46,서울특별시 강북구 미아동 222-100,155,5,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료

In [18]:
public = df[df['주차장구분'] == '공영']

In [19]:
public.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 444 entries, 0 to 513
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   주차장관리번호    444 non-null    object
 1   주차장명       444 non-null    object
 2   주차장구분      444 non-null    object
 3   주차장유형      444 non-null    object
 4   소재지도로명주소   358 non-null    object
 5   소재지지번주소    408 non-null    object
 6   주차구획수      444 non-null    int64
 7   급지구분       444 non-null    object
 8   부제시행구분     444 non-null    object
 9   운영요일       444 non-null    object
 10  평일운영시작시각   444 non-null    object
 11  평일운영종료시각   444 non-null    object
 12  토요일운영시작시각  444 non-null    object
 13  토요일운영종료시각  444 non-null    object
 14  공휴일운영시작시각  444 non-null    object
 15  공휴일운영종료시각  444 non-null    object
 16  요금정보       444 non-null    object
dtypes: int64(1), object(16)
memory usage: 62.4+ KB

In [20]:
public.head()

,주차장관리번호,주차장명,주차장구분,주차장유형,소재지도로명주소,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,평일운영종료시각,토요일운영시작시각,토요일운영종료시각,공휴일운영시작시각,공휴일운영종료시각,요금정보
0,108-1-000030,아카데미,공영,노상,서울특별시 강북구 4.19로25길,서울특별시 강북구 인수동 543-76,37,3,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
1,108-2-000026,수유쌈지,공영,노외,서울특별시 강북구 도봉로 265,서울특별시 강북구 수유동 612-6,19,1,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
2,108-1-000031,교육청길,공영,노상,서울특별시 강북구 도봉로20가길 3,서울특별시 강북구 송중동 137-19,80,3,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료
3,108-2-000016,오패산,공영,노외,서울특별시 강북구 도봉로34길 54,서울특별시 강북구 미아동 133-100,76,5,미시행,평일+토요일,0:00,23:59,0:00,23:59,0:00,0:00,유료
4,108-2-000005,미아동,공영,노외,서울특별시 강북구 도봉로61길 46,서울특별시 강북구 미아동 222-100,155,5,미시행,평일+토요일+공휴일,0:00,23:59,0:00,23:59,0:00,23:59,유료

In [21]:
# 구군 파생변수 생성
public['소재지도로명주소'].unique

<bound method Series.unique of 0          서울특별시 강북구 4.19로25길
1           서울특별시 강북구 도봉로 265
2         서울특별시 강북구 도봉로20가길 3
3         서울특별시 강북구 도봉로34길 54
4         서울특별시 강북구 도봉로61길 46
                ...
509    서울특별시 영등포구 여의대방로45길 18
510       서울특별시 영등포구 선유동1로 80
511       서울특별시 영등포구 영등포로 405
512        서울특별시 강서구 방화대로8길 3
513     서울특별시 성북구 북악산로 949-60
Name: 소재지도로명주소, Length: 444, dtype: object>

In [23]:
public['소재지지번주소'].unique

<bound method Series.unique of 0       서울특별시 강북구 인수동 543-76
1        서울특별시 강북구 수유동 612-6
2       서울특별시 강북구 송중동 137-19
3      서울특별시 강북구 미아동 133-100
4      서울특별시 강북구 미아동 222-100
               ...
509                      NaN
510                      NaN
511                      NaN
512                      NaN
513                      NaN
Name: 소재지지번주소, Length: 444, dtype: object>

In [48]:
public["구군"] = public["소재지지번주소"].str.split(expand=True)[1]

C:\Users\GnTRnD\AppData\Local\Temp\ipykernel_8416\3434165801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  public["구군"] = public["소재지지번주소"].str.split(expand=True)[1]

In [27]:
public.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 444 entries, 0 to 513
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   주차장관리번호    444 non-null    object
 1   주차장명       444 non-null    object
 2   주차장구분      444 non-null    object
 3   주차장유형      444 non-null    object
 4   소재지도로명주소   358 non-null    object
 5   소재지지번주소    408 non-null    object
 6   주차구획수      444 non-null    int64
 7   급지구분       444 non-null    object
 8   부제시행구분     444 non-null    object
 9   운영요일       444 non-null    object
 10  평일운영시작시각   444 non-null    object
 11  평일운영종료시각   444 non-null    object
 12  토요일운영시작시각  444 non-null    object
 13  토요일운영종료시각  444 non-null    object
 14  공휴일운영시작시각  444 non-null    object
 15  공휴일운영종료시각  444 non-null    object
 16  요금정보       444 non-null    object
 17  구군         408 non-null    object
dtypes: int64(1), object(17)
memory usage: 65.9+ KB

In [38]:
public["구군"]

0      강북구
1      강북구
2      강북구
3      강북구
4      강북구
      ...
509    NaN
510    NaN
511    NaN
512    NaN
513    NaN
Name: 구군, Length: 444, dtype: object

In [49]:
public['구군']

0      False
1      False
2      False
3      False
4      False
       ...
509    False
510    False
511    False
512    False
513    False
Name: 구군, Length: 444, dtype: bool

In [51]:
public['구군'] = public['구군'].fillna(public["소재지도로명주소"].str.split(expand=True)[1])

C:\Users\GnTRnD\AppData\Local\Temp\ipykernel_8416\4021465759.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  public['구군'] = public['구군'].fillna(public["소재지도로명주소"].str.split(expand=True)[1])

In [52]:
public['구군']

0       강북구
1       강북구
2       강북구
3       강북구
4       강북구
       ...
509    영등포구
510    영등포구
511    영등포구
512     강서구
513     성북구
Name: 구군, Length: 444, dtype: object

In [53]:
public.to_csv("results/parking_space_list.csv", index = False)